Product_CategoryModel/Models/ErrorViewModel.cs
namespace Product_CategoryModel.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Product_CategoryModel/Controllers/CategoryController.cs
using DataAccessLayer.Data;
using DataAccessLayer.Interface;
using Microsoft.AspNetCore.Mvc;
using ModelLayer.DB;

namespace Product_CategoryModel.Controllers
{
    public class CategoryController : Controller
    {
        private readonly Icategory _context;
        public CategoryController(Icategory context) 
        { 
            _context = context;
        }
        [HttpGet]
        public IActionResult Index()
        {
            var data = _context.GetAll().ToList();
            return View(data);
        }
        [HttpGet]   
        public IActionResult AddCat()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddCat(Category category)
        {
            if(category == null)
            {
                return PartialView("Error");
            }
            _context.Add(category);
            _context.save();

            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult EditCat(int id)
        {
            var data = _context.Get(x => x.categoryId == id);
            return View(data);
        }
        [HttpPost]
        public IActionResult EditCat(Category category)
        {
            if(category == null) { return PartialView("Error"); }
            _context.Update(category);
            _context.save();
            return RedirectToAction("Index");
        }
        [HttpPost]
        public IActionResult DeleteCat(Category category)
        {
            if (category.categoryId == 0) {return PartialView("Error"); } 
            var data = _context.Get(x => x.categoryId == category.categoryId);
            _context.Remove(data);
            _context.save();
            return RedirectToAction("Index");
        }

    }
}

Product_CategoryModel/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Product_CategoryModel.Models;
using System.Diagnostics;

namespace Product_CategoryModel.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Product_CategoryModel/Controllers/ProductController.cs
using DataAccessLayer.Interface;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ModelLayer.DB;

namespace Product_CategoryModel.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProduct _product;
        private readonly Icategory _category;
        public ProductController(IProduct product, Icategory category)
        {
            _product = product;
            _category = category;

        }
        public IActionResult Index()
        {
           var data= _product.GetAll().ToList();
            //ViewBag.Data = new SelectList(datalist, "categoryId", "CategoryName");
            
            return View(data);
        }
        [HttpGet] 
        public IActionResult AddProd()
        {
            IEnumerable<SelectListItem> datalist = _category.GetAll().ToList().Select(x => new SelectListItem
            {
                Text = x.CategoryName,
                Value = x.categoryId.ToString()
            });
            ViewBag.datalistt=datalist;
            return View();
        }
        [HttpPost]
        public IActionResult AddProd(Product product)
        {
            if (product != null)
            {
                _product.Add(product);
                _product.save();
                return RedirectToAction("Index");
            }
            return PartialView("Error");
        }
        [HttpGet]
        public IActionResult EditProd(int id)
        {
            var data = _product.Get(x => x.productId == id);
            return View(data);
        }
        [HttpPost]
        public IActionResult EditProd(Product product)
        {
            if(product.productId == 0) { return PartialView("Error"); }
            _product.update(product);
            _product.save();
            return RedirectToAction("Index");
        }
        [HttpPost]
        public IActionResult DeleteProd(Product product)
        {
            if (product.productId == 0) { return PartialView("Error"); }
            _product.Remove(product);
            _product.save();
            return RedirectToAction("Index");
        }
    }
}

Product_CategoryModel/Views/Category/AddCat.cshtml
@model ModelLayer.DB.Category
<h1>Create Category</h1>
<form method="post">
    <div class="mb-3">
        <label class="form-label">Category Name</label>
        <input type="text" class="form-control" asp-for="CategoryName" />
    </div>
    <div class="mb-3">
        <label class="form-label">Display Order</label>
        <input type="text" class="form-control" asp-for="DisplayOrder" />
    </div>
    <button type="submit" class="btn btn-primary">Add Employee</button>
</form>

Product_CategoryModel/Views/Category/EditCat.cshtml
@model ModelLayer.DB.Category

<h1>Edit Category</h1>

<form method="Put" class="mt-5">
    <div class="mb-3">
        <label class="form-label">Id</label>
        <input type="text" class="form-control" asp-for="categoryId" readonly />
    </div>
    <div class="mb-3">
        <label class="form-label">CategoryName</label>
        <input type="text" class="form-control" asp-for="CategoryName"/>
    </div>
    <div class="mb-3">
        <label class="form-label">DisplayOrder</label>
        <input type="text" class="form-control" asp-for="DisplayOrder"/>
    </div>
    <button type="submit" class="btn btn-primary">Edit Category</button>
    <div class="w-75 btn-group" role="group">
        <button class="btn btn-danger mx-2" asp-controller="Category" asp-action="DeleteCat"><i class="bi bi-trash-fill"></i>Delete</button>
    </div>
</form>

Product_CategoryModel/Views/Category/Index.cshtml
@model IEnumerable<ModelLayer.DB.Category>
<div class="container">
    <div class="row pt-4 pb-23">
        <div class="col-6">
            <div class="text-primary">
                Category List
            </div>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Category" asp-action="AddCat" class="btn btn-primary"> Create New Summary</a>
        </div>
    </div>
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Category Name </th>
                <th>Display Order</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.CategoryName</td>
                    <td>@item.DisplayOrder</td>
                    <td>
                        <div class="w-75 btn-group" role="group">
                            <a asp-controller="Category" asp-action="EditCat" asp-route-id="@item.categoryId" class="btn btn-primary mx-2"><i class="bi bi-pencil-square"></i>Edit</a>
                        </div>

                    </td>

                </tr>
            }
        </tbody>
    </table>
</div>

Product_CategoryModel/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Product_CategoryModel/Views/Product/AddProd.cshtml
@model ModelLayer.DB.Product
<h1>Create Product</h1>
<form method="post">
    <div class="mb-3">
        <label class="form-label">Title</label>
        <input type="text" class="form-control" asp-for="Title" />
    </div>
    <div class="mb-3">
        <label class="form-label">Description</label>
        <input type="text" class="form-control" asp-for="Description" />
    </div>
    <div class="mb-3">
        <label class="form-label">ISBN</label>
        <input type="text" class="form-control" asp-for="ISBN" />
    </div>
    <div class="mb-3">
        <label class="form-label">Author</label>
        <input type="text" class="form-control" asp-for="Author" />
    </div>
    <div class="mb-3">
        <label class="form-label">ListPrice</label>
        <input type="number" class="form-control" asp-for="ListPrice" />
    </div>
    <div class="mb-3">
        <label class="form-label">Price50</label>
        <input type="number" class="form-control" asp-for="price50" />
    </div>
    <div class="mb-3">
        <label class="form-label">Price100</label>
        <input type="number" class="form-control" asp-for="price100" />
    </div>
    <div class="mb-3">
        <label class="form-label">Category</label>
        <select asp-for="category_Id" asp-items="ViewBag.datalistt" class="form-select border-0 shadow">
            <option disabled selected>--Select Category--</option>
        </select>
    </div>
    <div class="mb-3">
        <label class="form-label">Image Url</label>
        <input type="text" class="form-control" asp-for="ImageUrl" />
    </div>
   
    <button type="submit" class="btn btn-primary">Add Product</button>
</form>

Product_CategoryModel/Views/Product/EditProd.cshtml
@model ModelLayer.DB.Product
<h1>Edit Product</h1>

<form method="post" class="mt-5">
    <div class="mb-3">
        <label class="form-label">Id</label>
        <input type="text" class="form-control" asp-for="productId" readonly />
    </div>
    <div class="mb-3">
        <label class="form-label">Title</label>
        <input type="text" class="form-control" asp-for="Title" />
    </div>
    <div class="mb-3">
        <label class="form-label">Description</label>
        <input type="text" class="form-control" asp-for="Description" />
    </div>
     <div class="mb-3">
        <label class="form-label">ISBN</label>
        <input type="text" class="form-control" asp-for="ISBN" />
    </div>
    <div class="mb-3">
        <label class="form-label">Author</label>
        <input type="text" class="form-control" asp-for="Author" />
    </div>
    <div class="mb-3">
        <label class="form-label">ListPrice</label>
        <input type="text" class="form-control" asp-for="ListPrice" />
    </div>
    <div class="mb-3">
        <label class="form-label">Price50</label>
        <input type="text" class="form-control" asp-for="price50" />
    </div>
    <div class="mb-3">
        <label class="form-label">Price100</label>
        <input type="text" class="form-control" asp-for="price100" />
    </div>
    <button type="submit" class="btn btn-primary">Edit Product</button>
    <div class="w-75 btn-group" role="group">
        <button class="btn btn-danger mx-2" asp-controller="Product" asp-action="DeleteProd"><i class="bi bi-trash-fill"></i>Delete</button>
    </div>
</form>

Product_CategoryModel/Views/Product/Index.cshtml
@model IEnumerable<ModelLayer.DB.Product>
<div class="container">
    <div class="row pt-4 pb-23">
        <div class="col-6">
            <div class="text-primary">
                Product List
            </div>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Product" asp-action="Addprod" class="btn btn-primary"> Create New Summary</a>
        </div>
    </div>
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Title </th>
                <th>Description</th>
                <th>ISBN</th>
                <th>Author</th>
                <th>ListPrice</th>
                <th>Price50</th>
                <th>Price100</th>
            
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Title</td>
                    <td>@item.Description</td>
                    <td>@item.ISBN</td>
                    <td>@item.Author</td>
                    <td>@item.ListPrice</td>
                    <td>@item.price50</td>
                    <td>@item.price100</td>

                    
                  

                    <td>
                        <div class="w-75 btn-group" role="group">
                            <a asp-controller="Product" asp-action="EditProd" asp-route-id="@item.productId" class="btn btn-primary mx-2"><i class="bi bi-pencil-square"></i>Edit</a>
                        </div>

                    </td>

                </tr>
            }
        </tbody>
    </table>
</div>

Product_CategoryModel/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Product_CategoryModel</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Product_CategoryModel.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Product_CategoryModel</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Category</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Product</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Product_CategoryModel - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>